### PR TITLE
Added support for DejaVu Sans

### PR DESCRIPTION
**Pull request by ahmadsalim**

### CODE REVIEW

**Comment by ahmadsalim** [comment]
It is not as pretty as Luxi Mono, but it is free.
If anyone has a better suggestion, it should be easy to change.

**Comment by david-christiansen** [comment]
Instead of the `freefonts` option, I would think that `dejavu` was a better name. This allows support for one or two other monospace fonts to be added, in case DejaVu doesn't fit well with the existing ones.

**Comment by ahmadsalim** [comment]
@david-christiansen OK, I renamed the option.

**Comment by david-christiansen** [comment]
Great, thanks!

Note also that Luxi Mono is gratis, so it's not like people need to pay for it.

**Pull request merged**
